name: Android CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_VERSION: "25.1.8937393"
      ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk
      ANDROID_NDK_HOME: ${{ runner.tool_cache }}/android-ndk
      CMAKE_BUILD_TYPE: Release
      OPENCV_INSTALL_DIR: ${{ runner.home }}/opencv-install
      FAISS_INSTALL_DIR: ${{ runner.home }}/faiss-install
      HDF5_INSTALL_DIR: ${{ runner.home }}/hdf5-install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          ndk-package: "ndk;${{ env.ANDROID_NDK_VERSION }}"
          arch: arm64-v8a
          target: default

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build git build-essential libtbb-dev libomp-dev

      # Build HDF5 for Android
      - name: Clone HDF5 repository
        run: git clone --depth 1 https://github.com/HDFGroup/hdf5.git

      - name: Configure and build HDF5
        working-directory: hdf5
        run: |
          mkdir -p build-android && cd build-android
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=${HDF5_INSTALL_DIR} \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_TESTING=OFF \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -GNinja
          ninja install

      # Build OpenCV for Android
      - name: Clone OpenCV repositories
        run: |
          git clone --depth 1 https://github.com/opencv/opencv.git
          git clone --depth 1 https://github.com/opencv/opencv_contrib.git

      - name: Configure and build OpenCV
        working-directory: opencv
        run: |
          mkdir -p build-android && cd build-android
          cmake .. \
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
            -DCMAKE_INSTALL_PREFIX=${OPENCV_INSTALL_DIR} \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_TESTS=OFF \
            -DBUILD_PERF_TESTS=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DBUILD_opencv_python=OFF \
            -DWITH_OPENMP=ON \
            -DWITH_TBB=ON \
            -DWITH_IPP=ON \
            -DWITH_OPENCL=OFF \
            -DOPENCV_GENERATE_PKGCONFIG=ON \
            -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
            -DOPENCV_ENABLE_NONFREE=ON \
            -DBUILD_opencv_wechat_qrcode=OFF \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -GNinja
          ninja install

      # Build FAISS for Android
      - name: Clone FAISS repository
        run: git clone --depth 1 https://github.com/facebookresearch/faiss.git

      - name: Configure and build FAISS
        working-directory: faiss
        run: |
          mkdir -p build-android && cd build-android
          cmake .. \
            -DFAISS_ENABLE_GPU=OFF \
            -DFAISS_ENABLE_PYTHON=OFF \
            -DFAISS_ENABLE_TESTS=OFF \
            -DFAISS_ENABLE_BENCHMARKS=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${FAISS_INSTALL_DIR} \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -GNinja
          ninja install

      # Build main CMake project for Android
      - name: Configure and build project
        run: |
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DOpenCV_DIR=${OPENCV_INSTALL_DIR}/sdk/native/jni \
            -DFAISS_ROOT=${FAISS_INSTALL_DIR} \
            -DCMAKE_PREFIX_PATH=${HDF5_INSTALL_DIR} \
            -GNinja
          ninja
